version: '3'
services:
  app:
    image: my-spring-app:staging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - my-app-network
    restart: always

networks:
  my-app-network:
    driver: bridge
