version: '3'
services:
  app:
    image: my-spring-app:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-app-network
    volumes:
      - ./logs:/app/logs
    restart: always

networks:
  my-app-network:
    driver: bridge
